---
experiment:
  name: IVR/German/German
dataset:
  data_dir: dataset/German
  dataset: German
  splitname: compositional-split-natural
model_params:
  nlayers: 2
  emb_dim: 300
  image_extractor: resnet18
training:
  batch_size: 4
  load:
  lr: 5.0e-05
  lrg: 0.001
  cosine_scale: 20
  max_epochs: 100
  save_every: 10000
  test_batch_size: 4
  test_set: val
  topk: 1
  wd: 5.0e-05
  workers: 4
  update_features: false
  lambda_rep: 1
  lambda_grad: 10